"""Add journal entries table

Revision ID: a7828e1ccfd9
Revises: 
Create Date: 2025-01-20 08:13:51.627749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7828e1ccfd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('mood', sa.String(length=64), nullable=False),
    sa.Column('gratitude', sa.Text(), nullable=False),
    sa.Column('room_for_growth', sa.Text(), nullable=False),
    sa.Column('thoughts', sa.Text(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
